name: xeus-python-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - jsonschema
  - numpy >1.12
  - scipy
  - jinja2
  - plotly
  - nbformat
  - pip:
    - ./cosapp.tar.gz