name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - jsonschema
  - numpy<2
  - scipy
  - wrapt
  - jinja2
  - plotly
  - nbformat
  - pip:
    - ./cosapp.tar.gz