name: cosapp_docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy<2
  - pytest
  - jsonschema
  - pandas
  - jinja2
  - sphinx<8.2
  - nbsphinx
  - sphinx-copybutton
  - sphinx-mdinclude>0.5.3
  - sphinxcontrib-mermaid<1
  - watchdog
  - requests_ntlm
  - ipykernel
  - plotly
  - pyfmi
  - pythonfmu
  - asv