name: cosapp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=py_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py38h1e0a361_0
  - assimulo=3.2=py38hae37d14_3
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38h1e0a361_1000
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.1=py38h5bae8af_0
  - chardet=3.0.4=py38h32f6830_1006
  - cryptography=3.0=py38h766eaa4_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.16=py38h32f6830_1
  - entrypoints=0.3=py38h32f6830_1001
  - fmilib=2.2=he1b5a44_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py38h32f6830_0
  - importlib_metadata=1.7.0=0
  - iniconfig=1.0.1=pyh9f0ad1d_0
  - ipykernel=5.3.4=py38h23f93f0_0
  - ipython=7.17.0=py38h1cdfbd6_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.2=py38h32f6830_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_14
  - libgfortran-ng=7.5.0=hdf63c60_14
  - libgomp=9.3.0=h24d8f2e_14
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libsodium=1.0.18=h516909a_0
  - libstdcxx-ng=9.3.0=hdf63c60_14
  - libxml2=2.9.10=h72b56ed_2
  - libxslt=1.1.33=h572872d_1
  - lxml=4.5.2=py38hbb43d70_0
  - markupsafe=1.1.1=py38h1e0a361_1
  - metis=5.1.0=he1b5a44_1005
  - mistune=0.8.4=py38h1e0a361_1001
  - more-itertools=8.4.0=py_0
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.7=py_0
  - nbsphinx=0.7.1=pyh9f0ad1d_0
  - ncurses=6.2=he1b5a44_1
  - notebook=6.1.0=py38h32f6830_0
  - ntlm-auth=1.5.0=pyh9f0ad1d_0
  - numpy=1.19.1=py38h8854b6b_0
  - openssl=1.1.1g=h516909a_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.0=py38h950e882_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pip=20.2=py_0
  - plotly=4.9.0=pyh9f0ad1d_0
  - pluggy=0.13.1=py38h32f6830_2
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfmi=2.7.4=py38hab2c0dc_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.16.0=py38h1e0a361_0
  - pysocks=1.7.1=py38h32f6830_1
  - pytest=6.0.1=py38h32f6830_0
  - python=3.8.5=h4d41432_2_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - pyzmq=19.0.2=py38ha71036d_0
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=pyh9f0ad1d_0
  - requests_ntlm=1.1.0=py_0
  - retrying=1.3.3=py_2
  - scipy=1.5.2=py38h8c5af15_0
  - send2trash=1.5.0=py_0
  - setuptools=49.2.1=py38h32f6830_0
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=3.1.2=py_0
  - sphinx-copybutton=0.3.0=pyh9f0ad1d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.32.3=hcee41ef_1
  - suitesparse=5.7.2=h717dc36_0
  - sundials=5.2.0=h0186668_1
  - tbb=2020.1=hc9558a2_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - tornado=6.0.4=py38h1e0a361_1
  - traitlets=4.3.3=py38h32f6830_1
  - urllib3=1.25.10=py_0
  - watchdog=0.10.3=py38h32f6830_1
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py38h32f6830_1
  - openpyxl=3.0.5
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.2=he1b5a44_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - pythonfmu
