name: cosapp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - assimulo=3.2.3
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - cryptography=3.4.4
  - decorator=4.4.2
  - defusedxml=0.7.1
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fmilib=2.2.3
  - icu=68.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=3.7.2
  - iniconfig=1.1.1
  - ipykernel=5.5.0
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=2.11.3
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lxml=4.6.2
  - markupsafe=1.1.1
  - metis=5.1.0
  - mistune=0.8.4
  - more-itertools=8.7.0
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nbsphinx=0.8.1
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.2.0
  - ntlm-auth=1.5.0
  - numpy=1.20.1
  - openpyxl=3.0.6
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.12
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - plotly=4.14.3
  - pluggy=0.13.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - ptyprocess=0.7.0
  - py=1.10.0
  - pycparser=2.20
  - pyfmi=2.8.5
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pythonfmu=0.6.2
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - readline=8.0
  - requests=2.25.1
  - requests_ntlm=1.1.0
  - retrying=1.3.3
  - scipy=1.6.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sphinx=3.5.2
  - sphinx-copybutton=0.3.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.34.0
  - suitesparse=5.7.2
  - sundials=5.4.0
  - tbb=2020.2
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - typing=3.7.4.3
  - tzdata=2021a
  - urllib3=1.26.3
  - watchdog=2.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
